name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - JohnRDOrazio
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the API where you using when you noticed the bug?
      options:
        - v1
        - v2
        - v3 (Default)
        - dev (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which browser or browsers are you seeing the problem on? (can select more than one)
      multiple: true
      options:
        - Chrome
        - Edge
        - Firefox
        - Safari
  - type: textarea
    id: error-messages
    attributes:
      label: Relevant error messages
      description: If there are any error messages related to the bug, please add them here. This will be automatically formatted into code, so no need for backticks.
      render: shell
